#!/usr/bin/python
# -*- coding: utf-8 -*-

import csv
import json

# Read the CSV and add the data to a dictionary...
csvfile = open('cleaned_hm.csv', 'r')
jsonfile = open('happy.json', 'w')

fieldnames = ("is_negated",	"is_regex",	"replace_target", "rule_id", "target", "target_match")

# Write data to a JSON file...
reader = csv.DictReader( csvfile, fieldnames)
for row in reader:
    json.dump(row, jsonfile, indent=4)
    jsonfile.write('\n')
